### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Lolothepro** [KostromDan/Mods-Decompiler-GUI#7]
```
Traceback (most recent call last):
  File "MDG.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "MDGUi\generate_ui.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "MDGUtil\FileUtils.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "MDGLogic\InitialisationThread.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "MDGUtil\PathUtils.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "win32com\client\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "win32com\client\gencache.py", line 764, in <module>
  File "win32com\client\gencache.py", line 63, in __init__
  File "win32com\client\gencache.py", line 122, in _LoadDicts
_pickle.UnpicklingError: invalid load key, '\x00'.
[5844] Failed to execute script 'MDG' due to unhandled exception!

```

Hey, I have this error, is it fixable?

**Comment by KostromDan** [comment]
This error happened when you performed some actions or just on the first launch of the program?

**Comment by Lolothepro** [comment]
> This error happened when you performed some actions or just on the first launch of the program?

When the program is launched, the previous version works
